modelname:              "./models/train-faster.model"
threads:                50
rawdir:                 "/nethome/sheneman/src/images/raw"
bindir:                 "/nethome/sheneman/src/images/binary"
importance:             "./feature_importance.csv"
trainlist:              "./trainlist.txt"
validationlist:         "./validationlist.txt"
testlist:               "./testlist.txt"
