rf_model:               "./rf.model"
xgb_model:              "./xgb.model"
mlp_model:              "./mlp.model"
threads:                50
rawdir:                 "/nethome/sheneman/src/MTY_100_revised/original/slim"
bindir:                 "/nethome/sheneman/src/MTY_100_revised/original/binary_LD"
importance:             "./feature_importance.csv"
trainlist:              "./trainlist.txt"
validationlist:         "./validationlist.txt"
testlist:               "./testlist.txt"
